### PR TITLE
Add support for ng-attr-placeholder

### PR DESCRIPTION
**Pull request by akkunchoi**
I often use both angular-translate and placeholder.

For example:

The code

```
<input type="text" placeholder="{{'translate_key123' | translate}}">
```

flashes eyesores "{{'translate_key123' | translate}}".

Angular's [ng-attr-\* attribute bindings](https://docs.angularjs.org/guide/directive#-ngattr-attribute-bindings) solves this unpleasant.

This pull-request also upgrade ngmin to [ngAnnotate](https://github.com/olov/ng-annotate), becase ngmin doesn't work simple function() use.

### CODE REVIEW

**Comment by cvn** [comment]
This looks really good. I'm happy about getting rid of ngMin. I'm gonna test it locally.

**Comment by cvn** [comment]
Hey @akkunchoi, I'm a little confused. I did some tests and the current release of angular-shims-placeholder (without your changes) works well with ng-attr-placeholder. I just added an example to the [demo page](http://cvn.github.io/angular-shims-placeholder) to prove it to myself. Were you seeing problems?

**Comment by akkunchoi** [comment]
The current release of angular-shims-placeholder has no problem. I was mistaken.

Thank you for your thorough testing and I'm sorry to trouble you.

**Comment by cvn** [comment]
It's alright. It was worth spending some time on. I'm glad to have learned about the ngAttr attribute bindings. As part of my testing, I found a bug where an undefined ngAttrPlaceholder on a password would actually display "undefined" for the placeholder. I fixed that in the latest release. I also merged in your ngAnnotate commit. Thanks for that.

**Pull request closed without merging**
